In [9]:
%matplotlib inline

In [1]:
import pandas

In [19]:
data = pandas.read_csv('C:\\Users\\Alexis\\Downloads\\engsoccerdata-master\\data-raw\\france.csv', index_col=0, parse_dates=[1], infer_datetime_format=True)

In [23]:
data.head(6)

,Date,Season,home,visitor,FT,hgoal,vgoal,division,tier,totgoal,goaldif,result
1,1933-07-01,1932,CA Paris (alt),AS Cannes,5-1,5,1,1,1,6,4,H
2,1933-07-01,1932,SC Fives Lille,FC Sete,4-2,4,2,1,1,6,2,H
3,1933-07-01,1932,Olympique Marseille,OGC Nice,4-0,4,0,1,1,4,4,H
4,1933-07-01,1932,SC Nimes,Olympique Lillois Lille,3-3,3,3,1,1,6,0,D
5,1933-07-01,1932,FC Antibes,Stade Rennes,1-1,1,1,1,1,2,0,D
6,1933-07-01,1932,Stade Olympique Montpellierain,Racing Club de France,1-0,1,0,1,1,1,1,H

In [28]:
data.groupby(by=data.Season).mean()

           hgoal     vgoal  division  tier   totgoal   goaldif
Season
1932    2.818681  1.686813       1.0   1.0  4.505495  1.131868
1933    2.458333  1.458333       1.0   1.0  3.916667  1.000000
1934    2.350000  1.454167       1.0   1.0  3.804167  0.895833
1935    2.275000  1.350000       1.0   1.0  3.625000  0.925000
1936    1.991667  1.312500       1.0   1.0  3.304167  0.679167
1938    1.970833  1.220833       1.0   1.0  3.191667  0.750000
1945    2.153595  1.382353       1.0   1.0  3.535948  0.771242
1946    2.235294  1.305882       1.0   1.0  3.541176  0.929412
1947    2.277778  1.401961       1.0   1.0  3.679739  0.875817
1948    2.395425  1.323529       1.0   1.0  3.718954  1.071895
1949    2.186275  1.349673       1.0   1.0  3.535948  0.836601
1950    2.032680  1.287582       1.0   1.0  3.320261  0.745098
1951    2.173203  1.261438       1.0   1.0  3.434641  0.911765
1952    1.996732  1.147059       1.0   1.0  3.143791  0.849673
1953    1.934641  1.166667       1.0   1.0  3.101307  0.767974
1954    2.235294  1.202614       1.0   1.0  3.437908  1.032680
1955    2.088235  1.212418       1.0   1.0  3.300654  0.875817
1956    2.029412  1.336601       1.0   1.0  3.366013  0.692810
1957    2.042484  1.303922       1.0   1.0  3.346405  0.738562
1958    1.997368  1.321053       1.0   1.0  3.318421  0.676316
1959    1.997368  1.363158       1.0   1.0  3.360526  0.634211
1960    1.936842  1.210526       1.0   1.0  3.147368  0.726316
1961    1.918421  1.218421       1.0   1.0  3.136842  0.700000
1962    1.886842  1.234211       1.0   1.0  3.121053  0.652632
1963    2.045752  1.147059       1.0   1.0  3.192810  0.898693
1964    1.764706  1.075163       1.0   1.0  2.839869  0.689542
1965    2.028947  1.102632       1.0   1.0  3.131579  0.926316
1966    1.676316  0.963158       1.0   1.0  2.639474  0.713158
1967    1.705263  0.931579       1.0   1.0  2.636842  0.773684
1968    1.764706  0.901961       1.0   1.0  2.666667  0.862745
...          ...       ...       ...   ...       ...       ...
1984    1.713158  0.863158       1.0   1.0  2.576316  0.850000
1985    1.636842  0.813158       1.0   1.0  2.450000  0.823684
1986    1.381579  0.713158       1.0   1.0  2.094737  0.668421
1987    1.492105  0.755263       1.0   1.0  2.247368  0.736842
1988    1.523684  0.844737       1.0   1.0  2.368421  0.678947
1989    1.526316  0.744737       1.0   1.0  2.271053  0.781579
1990    1.410526  0.707895       1.0   1.0  2.118421  0.702632
1991    1.336842  0.757895       1.0   1.0  2.094737  0.578947
1992    1.439474  0.892105       1.0   1.0  2.331579  0.547368
1993    1.423684  0.813158       1.0   1.0  2.236842  0.610526
1995    1.436842  0.844737       1.0   1.0  2.281579  0.592105
1996    1.442105  0.884211       1.0   1.0  2.326316  0.557895
1997    1.450980  0.908497       1.0   1.0  2.359477  0.542484
1998    1.483660  0.879085       1.0   1.0  2.362745  0.604575
1999    1.604575  0.967320       1.0   1.0  2.571895  0.637255
2000    1.450980  1.055556       1.0   1.0  2.506536  0.395425
2001    1.516340  0.823529       1.0   1.0  2.339869  0.692810
2002    1.344737  0.857895       1.0   1.0  2.202632  0.486842
2003    1.405263  0.921053       1.0   1.0  2.326316  0.484211
2004    1.347368  0.826316       1.0   1.0  2.173684  0.521053
2005    1.276316  0.857895       1.0   1.0  2.134211  0.418421
2006    1.321900  0.934037       1.0   1.0  2.255937  0.387863
2007    1.347368  0.936842       1.0   1.0  2.284211  0.410526
2008    1.286842  0.971053       1.0   1.0  2.257895  0.315789
2009    1.389474  1.021053       1.0   1.0  2.410526  0.368421
2010    1.342105  1.000000       1.0   1.0  2.342105  0.342105
2011    1.473684  1.042105       1.0   1.0  2.515789  0.431579
2012    1.468421  1.076316       1.0   1.0  2.544737  0.392105
2013    1.410526  1.039474       1.0   1.0  2.450000  0.371053
2014    1.410526  1.081579       1.0   1.0  2.492105  0.328947

[75 rows x 6 columns]

In [37]:
data[data.Season == (1932, 1950, 1980, 2010, 2014)].totgoal.hist(by=data.Season)

TypeError: invalid type comparison

In [44]:
data[data.Season.any(1938,1950)]

ValueError: No axis named 1938 for object type <class 'pandas.core.series.Series'>